// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Whitestone.WASP.Database;

#nullable disable

namespace Whitestone.WASP.Database.Migrations.MySQL
{
    [DbContext(typeof(WaspMysqlDbContext))]
    partial class WaspMysqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AlbumGenre", b =>
                {
                    b.Property<int>("AlbumsId")
                        .HasColumnType("int");

                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.HasKey("AlbumsId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("AlbumGenre");
                });

            modelBuilder.Entity("AlbumPersonGroupPersonRelationPerson", b =>
                {
                    b.Property<int>("AlbumPersonGroupPersonRelationsId")
                        .HasColumnType("int");

                    b.Property<int>("PersonsId")
                        .HasColumnType("int");

                    b.HasKey("AlbumPersonGroupPersonRelationsId", "PersonsId");

                    b.HasIndex("PersonsId");

                    b.ToTable("AlbumPersonGroupPersonRelationPerson");
                });

            modelBuilder.Entity("AlbumRecordLabel", b =>
                {
                    b.Property<int>("AlbumsId")
                        .HasColumnType("int");

                    b.Property<int>("RecordLabelsId")
                        .HasColumnType("int");

                    b.HasKey("AlbumsId", "RecordLabelsId");

                    b.HasIndex("RecordLabelsId");

                    b.ToTable("AlbumRecordLabel");
                });

            modelBuilder.Entity("DiscMediaType", b =>
                {
                    b.Property<int>("DiscsId")
                        .HasColumnType("int");

                    b.Property<int>("MediaTypesId")
                        .HasColumnType("int");

                    b.HasKey("DiscsId", "MediaTypesId");

                    b.HasIndex("MediaTypesId");

                    b.ToTable("DiscMediaType");
                });

            modelBuilder.Entity("PersonTrackPersonGroupPersonRelation", b =>
                {
                    b.Property<int>("PersonsId")
                        .HasColumnType("int");

                    b.Property<int>("TrackPersonGroupPersonRelationsId")
                        .HasColumnType("int");

                    b.HasKey("PersonsId", "TrackPersonGroupPersonRelationsId");

                    b.HasIndex("TrackPersonGroupPersonRelationsId");

                    b.ToTable("PersonTrackPersonGroupPersonRelation");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Added")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CatalogueNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<ushort>("Published")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Upc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.AlbumCover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("Filesize")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId")
                        .IsUnique();

                    b.ToTable("AlbumCovers");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.AlbumCoverData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AlbumCoverId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.HasIndex("AlbumCoverId")
                        .IsUnique();

                    b.ToTable("AlbumCoversData");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.AlbumPersonGroupPersonRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("PersonGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("PersonGroupId");

                    b.ToTable("AlbumPersonGroupsRelations");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.Disc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<byte>("DiscNumber")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Discs");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.MediaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("MediaTypes");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<ushort>("Version")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.PersonGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ushort>("SortOrder")
                        .HasColumnType("smallint unsigned");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PersonGroups");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.RecordLabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("RecordLabels");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.StreamHistory", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("Played")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TrackStreamInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrackStreamInfoId");

                    b.ToTable("StreamHistory");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.StreamQueue", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("SortOrder")
                        .HasColumnType("smallint unsigned");

                    b.Property<int>("TrackStreamInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrackStreamInfoId");

                    b.ToTable("StreamQueue");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DiscId")
                        .HasColumnType("int");

                    b.Property<ushort>("Length")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<ushort>("TrackNumber")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("DiscId");

                    b.HasIndex("Title");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.TrackGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DiscId")
                        .HasColumnType("int");

                    b.Property<ushort>("GroupBeforeTrackNumber")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DiscId");

                    b.ToTable("TrackGroups");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.TrackPersonGroupPersonRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("PersonGroupId")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("PersonGroupId");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackPersonGroupsRelations");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.TrackStreamInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IncludeInAutoPlaylist")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastPlayed")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrackId")
                        .IsUnique();

                    b.HasIndex("IncludeInAutoPlaylist", "LastPlayed", "PlayCount");

                    b.ToTable("TrackStreamInfos");
                });

            modelBuilder.Entity("AlbumGenre", b =>
                {
                    b.HasOne("Whitestone.WASP.Database.Models.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whitestone.WASP.Database.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlbumPersonGroupPersonRelationPerson", b =>
                {
                    b.HasOne("Whitestone.WASP.Database.Models.AlbumPersonGroupPersonRelation", null)
                        .WithMany()
                        .HasForeignKey("AlbumPersonGroupPersonRelationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whitestone.WASP.Database.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlbumRecordLabel", b =>
                {
                    b.HasOne("Whitestone.WASP.Database.Models.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whitestone.WASP.Database.Models.RecordLabel", null)
                        .WithMany()
                        .HasForeignKey("RecordLabelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscMediaType", b =>
                {
                    b.HasOne("Whitestone.WASP.Database.Models.Disc", null)
                        .WithMany()
                        .HasForeignKey("DiscsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whitestone.WASP.Database.Models.MediaType", null)
                        .WithMany()
                        .HasForeignKey("MediaTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonTrackPersonGroupPersonRelation", b =>
                {
                    b.HasOne("Whitestone.WASP.Database.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whitestone.WASP.Database.Models.TrackPersonGroupPersonRelation", null)
                        .WithMany()
                        .HasForeignKey("TrackPersonGroupPersonRelationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.AlbumCover", b =>
                {
                    b.HasOne("Whitestone.WASP.Database.Models.Album", "Album")
                        .WithOne("AlbumCover")
                        .HasForeignKey("Whitestone.WASP.Database.Models.AlbumCover", "AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.AlbumCoverData", b =>
                {
                    b.HasOne("Whitestone.WASP.Database.Models.AlbumCover", "AlbumCover")
                        .WithOne("AlbumCoverData")
                        .HasForeignKey("Whitestone.WASP.Database.Models.AlbumCoverData", "AlbumCoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlbumCover");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.AlbumPersonGroupPersonRelation", b =>
                {
                    b.HasOne("Whitestone.WASP.Database.Models.Album", "Album")
                        .WithMany("AlbumPersonGroupPersonRelations")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whitestone.WASP.Database.Models.PersonGroup", "PersonGroup")
                        .WithMany("AlbumPersonGroupPersonRelations")
                        .HasForeignKey("PersonGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("PersonGroup");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.Disc", b =>
                {
                    b.HasOne("Whitestone.WASP.Database.Models.Album", "Album")
                        .WithMany("Discs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.StreamHistory", b =>
                {
                    b.HasOne("Whitestone.WASP.Database.Models.TrackStreamInfo", "TrackStreamInfo")
                        .WithMany("StreamHistory")
                        .HasForeignKey("TrackStreamInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackStreamInfo");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.StreamQueue", b =>
                {
                    b.HasOne("Whitestone.WASP.Database.Models.TrackStreamInfo", "TrackStreamInfo")
                        .WithMany("StreamQueue")
                        .HasForeignKey("TrackStreamInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackStreamInfo");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.Track", b =>
                {
                    b.HasOne("Whitestone.WASP.Database.Models.Disc", "Disc")
                        .WithMany("Tracks")
                        .HasForeignKey("DiscId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disc");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.TrackGroup", b =>
                {
                    b.HasOne("Whitestone.WASP.Database.Models.Disc", "Disc")
                        .WithMany("TrackGroups")
                        .HasForeignKey("DiscId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disc");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.TrackPersonGroupPersonRelation", b =>
                {
                    b.HasOne("Whitestone.WASP.Database.Models.Album", null)
                        .WithMany("TrackPersonGroupPersonRelations")
                        .HasForeignKey("AlbumId");

                    b.HasOne("Whitestone.WASP.Database.Models.PersonGroup", "PersonGroup")
                        .WithMany("TrackPersonGroupPersonRelations")
                        .HasForeignKey("PersonGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whitestone.WASP.Database.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonGroup");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.TrackStreamInfo", b =>
                {
                    b.HasOne("Whitestone.WASP.Database.Models.Track", "Track")
                        .WithOne("TrackStreamInfo")
                        .HasForeignKey("Whitestone.WASP.Database.Models.TrackStreamInfo", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.Album", b =>
                {
                    b.Navigation("AlbumCover")
                        .IsRequired();

                    b.Navigation("AlbumPersonGroupPersonRelations");

                    b.Navigation("Discs");

                    b.Navigation("TrackPersonGroupPersonRelations");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.AlbumCover", b =>
                {
                    b.Navigation("AlbumCoverData")
                        .IsRequired();
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.Disc", b =>
                {
                    b.Navigation("TrackGroups");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.PersonGroup", b =>
                {
                    b.Navigation("AlbumPersonGroupPersonRelations");

                    b.Navigation("TrackPersonGroupPersonRelations");
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.Track", b =>
                {
                    b.Navigation("TrackStreamInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Whitestone.WASP.Database.Models.TrackStreamInfo", b =>
                {
                    b.Navigation("StreamHistory");

                    b.Navigation("StreamQueue");
                });
#pragma warning restore 612, 618
        }
    }
}
