name: Build & Deploy Docker image
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: GitHub Container Registry
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Checkout Assets
      uses: actions/checkout@v4
      with:
        ref: assets
        path: lib
        fetch-depth: 0
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v3.0.3
      with:
        versionSpec: '6.0.x'
    - name: Execute GitVersion
      uses: gittools/actions/gitversion/execute@v3.0.3
      with:
        useConfigFile: true
    - name: Set semver variables (Prerelease)
      run: |
        echo "SegnoSharpSemVer=${{ env.GitVersion_MajorMinorPatch }}" >> "$GITHUB_ENV"
        echo "SegnoSharpSemVerFull=${{ env.GitVersion_FullSemVer }}" >> "$GITHUB_ENV"
    - name: 'Set semver variables (Release)'
      run: |
        echo "SegnoSharpSemVer=${{ env.GitVersion_MajorMinorPatch }}" >> "$GITHUB_ENV"
        echo "SegnoSharpSemVerFull=${{ env.GitVersion_MajorMinorPatch }}" >> "$GITHUB_ENV"
      if: startsWith(github.repository, 'refs/tags')
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to Docker Hub Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PAT }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        file: ./src/SegnoSharp/Dockerfile
        context: .
        push: true
        build-args: |
          SEGNOSHARP_SEMVER=${{ env.SegnoSharpSemVer }}
          SEGNOSHARP_SEMVER_FULL=${{ env.SegnoSharpSemVerFull }}
        tags: |
            ghcr.io/whitestone-no/segnosharp:${{ env.SegnoSharpSemVerFull }}
            ghcr.io/whitestone-no/segnosharp:latest  
            whitestoneno/segnosharp:${{ env.SegnoSharpSemVerFull }}

